version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - PORT=8080
    volumes:
      - ./.env:/root/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Database service (for future use)
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: trinetraguard
  #     POSTGRES_USER: trinetraguard
  #     POSTGRES_PASSWORD: trinetraguard
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

# volumes:
#   postgres_data:
