version: '3.8'

services:
  video-analysis-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ENVIRONMENT=development
      - DB_DRIVER=sqlite3
      - DB_NAME=video_analysis.db
      - STORAGE_VIDEOS_DIR=./videos
      - STORAGE_FINDER_DIR=./finder
      - STORAGE_MAX_FILE_SIZE=104857600
    volumes:
      - ./videos:/app/videos
      - ./finder:/app/finder
      - ./video_analysis.db:/app/video_analysis.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL service (optional, for production use)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: video_analysis
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - postgres

  # Redis service (optional, for caching)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - redis

volumes:
  postgres_data:
  redis_data: 